name: Continuous Integration

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ./AspNetMonsters.ApplicationInsights
    - name: Test
      run: dotnet test
      working-directory: ./AspNetMonsters.ApplicationInsights
      
